out = ['15\n', 
       '(1, 2, 3, 4, 5)\n', 
       '(CIS104B, CIS104B, CIS104B)\n', 
       '(HELLO!, dflsdfiuh, dkgh)\n', 
       'CIS104B\n', 
       '[lambda closure: x: 2]\n', 
       '15\n', 
       '\n', 
       '2\n', 
       '\n', 
       '(6, 120, 5040)\n', 
       '4\n', 
       'irst letter missing in this sentence?\n', 
       '15\n',
        '1\n', 
        '\n', 
        'true\n', 
        '13\n', 
        '18\n', 
        '(0, 32, Args of unequal length, Args not both tuples)\n', 
        '(0, 32, Args of unequal length, Args not both tuples)\n', 
        '(ad, be, cf)\n', 
        '(ad, be, cf)\n', 
        '(ad, be, cf)\n', 
        '7\n', 
        '4\n.   3\n.   .   T\n.   .   3\n.   .   .   T\n.   .   .   T\n.   .   .   T\n.   .   T\n.   2\n.   .   T\n.   .   T\n.   3\n.   .   T\n.   .   T\n.   .   0\n.   .   .   \n.   1\n.   .   T\n', 
        '5\n', 
        'Hello\tWorld.\nHai\n', 
        '7\n', 
        ' 4 6 8 10 12 14\n', 
        '(cba, daba le arroz al a zorra elabad)\n', 
        '\n', 
        '3\n', 
        '1\n', 
        '2\n', 
        'This is COP5550\n', 
        '15\n', 
        'Hello World.\n\n', 
        '6\n', 
        '3\n', 
        '3\n', 
        'abcdefghijklmnopqrstuvwxyz\n', 
        '1\t .\n$$$\n', 
        '2\n', 
        '6\n', 
        '(4, 2, 3)\n', 
        '(1, 2, 3)\n', 
        '(3)\n', 
        '(1, 2, 0, 1)\n', 
        'Move A to C\nMove A to B\nMove C to B\nMove A to C\nMove B to A\nMove B to C\nMove A to C\nMove A to B\nMove C to B\nMove C to A\nMove B to A\nMove C to B\nMove A to C\nMove A to B\nMove C to B\n\n', 
        '(0(), 1(T), 4(3(T,3(T,T,T),T),2(T,T),3(T,T,0()),1(T)))\n', 
        '<ARROW\n    <BINOP\n        x\n        EQ\n        0\n    >\n    Y\n    <AP\n        f\n        2\n    >\n>\n', 
        '14\n', 
        '(5, 7, 9)\n', 
        '10\n', 
        'error\n']
