name: python application test with github actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          make install
      - name: test with pytest
        run: |
          make test_ast
      - name: cleanup after test
        run: |
          make clean
