name: Python Application AST Testing with GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Setup Python 3.8 on Windows
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          make install

      - name: Test with pytest
        run: |
          make test_ast

      - name: Cleanup after test
        run: |
          make clean
